[tool.poetry]
name = "irpf-cei"
version = "1.0.0"
description = "Programa auxiliar para calcular custos de ações, ETFs e FIIs."
authors = ["staticdev <thiagocavila@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0.3"
click = "^7.1.1"
xlrd = "^1.2.0"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
flake8-bandit = "^2.1.2"
flake8-black = "^0.1.1"
flake8-bugbear = "^20.1.4"
flake8-import-order = "^0.18.1"
safety = "^1.8.7"
pytest = "^5.4.1"
codecov = "^2.0.22"
mypy = "^0.770"
coverage = {extras = ["toml"], version = "^5.0.4"}
pytest-cov = "^2.8.1"

[tool.poetry.scripts]
irpf-cei = "irpf_cei.console:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["irpf_cei"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
